### ISSUE TITLE
Create cheat sheet for mysql->c# datatypes

### ISSUE THREAD

**Issue by codyjmcb** [codyjmcb/golf_stuff#30]
What does a tinyint translate to in c#?

**Comment by iiiancampbell** [comment]
hey @codyjmcb , would be interested in contributing to this first time issue. feel free to assign it to me if this is okay!

**Comment by codyjmcb** [comment]
Hi @iiiancampbell, I have assigned you this issue. Admittedly I am still learning how to use github (vs. gitlab) so if there is anything else I need to do to allow you to complete this, let me know! Appreciate the help!

**Comment by iiiancampbell** [comment]
No worries!

I’m learning the ropes too, no stress.

Did you just want me to amend the existing readme with the MySQL>>C# data types?

**Comment by codyjmcb** [comment]
I'm about to add a document to Documentation/ called Database ReadMe.txt, it is from when I had attempted this project previously and served as a starting point for this one (I've since learned more and wanted to try again). If you could append this file with the respective data type alignments, that would be greatly appreciated!

Do you use Discord?? We could link on discord to make communication easier between the two of us!

**Comment by codyjmcb** [comment]
I added the file, note the contents of the file (as they relate to the DB Schema) are not 100% accurate with what exists in the actual database. This shouldn't affect the data type alignment!

**Comment by codyjmcb** [comment]
Also, I'm sure you know this, but please do NOT contribute directly to the main branch, I am still working on figuring out how to configure github repos in the way I prefer. You can create a branch, make the changes, and make a pull request. At which point I will review and merge them :)

**Comment by iiiancampbell** [comment]
Great,

I’ll work off that file tomorrow - currently 1am my time!

**Comment by codyjmcb** [comment]
Perfect! I appreciate it, have a good night!
